# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - ruby_folder_version: "23"
      ruby_gems_folder: "2.3.0"
      platform: "x86"

install:
  - SET "PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%"
  # Bundler downgrade should be removed when the issue is fixed upstream
  - gem uninstall bundler -x
  - gem install bundler -v "=1.10.6" --no-document
  - bundle install --retry 3 --jobs=%NUMBER_OF_PROCESSORS% --clean --deployment

build: off

test_script:
  - ruby -v
  - gem -v
  - bundle -v

matrix:
  fast_finish: true
